/*==============================================================
      AWS Application Load Balancer + Target groups
===============================================================*/

resource "aws_alb" "alb" {
  count              = var.create_alb == true ? 1 : 0
  name               = "${var.name}-alb"
  subnets            = var.subnets
  security_groups    = var.security_group
  load_balancer_type = "application"
  internal           = var.internal
  enable_http2       = var.internal
  idle_timeout       = 30
}

# ------- ALB Listener for HTTPS -------
resource "aws_alb_listener" "https_listener" {
  count             = var.create_alb == true ? 1 : 0
  load_balancer_arn = aws_alb.alb[0].id
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = var.ssl_policy
  certificate_arn   = var.certificate_arn

  default_action {
    type = "fixed-response"
    fixed_response {
      content_type = "text/plain"
      message_body = "no route"
      status_code  = "503"
    }
  }

  lifecycle {
    // ignore changes made by apps rules or CodeDeploy
    ignore_changes = [default_action]
  }
}

# ------- ALB Listener for HTTP -------
resource "aws_alb_listener" "http_listener" {
  count             = var.create_alb == true ? (var.enable_http == true ? 1 : 0) : 0
  load_balancer_arn = aws_alb.alb[0].id
  port              = var.port
  protocol          = "HTTP"

  default_action {
    type = "fixed-response"
    fixed_response {
      content_type = "text/plain"
      message_body = "no route"
      status_code  = "503"
    }
  }

  lifecycle {
    // to avoid changes generated by CodeDeploy changes
    ignore_changes = [default_action]
  }
}

# ------- Target Groups for ALB -------
resource "aws_alb_target_group" "target_group" {
  count                = var.create_target_group == true ? 1 : 0
  name                 = var.name
  port                 = var.port
  protocol             = var.protocol
  vpc_id               = var.vpc_id
  target_type          = var.tg_type
  deregistration_delay = 5

  health_check {
    enabled             = true
    interval            = var.health_check_interval
    path                = var.health_check_path
    port                = "traffic-port"
    protocol            = var.protocol
    timeout             = var.health_check_timeout
    healthy_threshold   = var.health_check_healthy_threshold
    unhealthy_threshold = var.health_check_unhealthy_threshold
    matcher             = var.health_check_matcher
  }

  lifecycle {
    create_before_destroy = true
  }
}